# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    paths:
      - '**.js'
      - ibr/**
      - .github/workflows/node.js.yml
    branches: [ master ]
    tags: [ ibr ]
  pull_request:
    paths:
      - '**.js'
      - ibr/**
      - .github/workflows/node.js.yml
    branches: [ master ]
    tags: [ ibr ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238  # v6.2.0
      with:
        node-version: ${{ matrix.node-version }}

    - name: ESLint Action
      run: npm install && npm run install-linter && npm run lint
      working-directory: ./ibr/ibr_sdk/

    - name: Build IBR dist package
      run: npm run build
      working-directory: ./ibr/ibr_sdk/

    - name: Tests
      run: npm test
      working-directory: ./ibr/ibr_sdk/
