# This workflow adds guids to any newly added entity types in the ontology and validates the ontology
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Ontology Validator

on:
  push:
    branches: [ master ]
    paths: 
      - ontology/yaml/**

  pull_request:
    branches: [ master ]
    paths: 
      - ontology/yaml/**

jobs:
  build:
  
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        
    - name: Get modified entity type files
      id: changed-entity-type-files
      uses: tj-actions/changed-files@v35
      with:
        files: '**/entity_types/*.yaml'
        
    - name: Install dependencies for ontology YAML validator 
      run: |
        python setup.py install
      working-directory: ./tools/validators/ontology_validator
        
    - name: Install dependencies for types GUID generator if any entity types files are changed
      if: steps.changed-entity-type-files.outputs.any_changed == 'true'
      run: |
        python setup.py install
      working-directory: ./tools/guid_generator/ontology

    - name: Run types GUID generator if any entity types files are changed
      if: steps.changed-entity-type-files.outputs.any_changed == 'true'
      run: |
        for file in ${{ steps.changed-entity-type-files.outputs.all_changed_files }}; do
          python types_guid_generator.py -f=../../../../$file
        done
      working-directory: ./tools/guid_generator/ontology/types_guid_generator

    - name: Commit files changed by types GUID generator
      if: ${{ github.event.pull_request != null}}
      uses: EndBug/add-and-commit@v9
      with:
        author_name: auto_type_guid_generator
        author_email: support-digitalbuildings@google.com
        message: 'Add GUIDs to new entity types'
    
    - name: Run ontology YAML validator on ontology extensions
      run: |
        python validator.py --original=../../../../ontology/yaml/resources  --interactive=False
      working-directory: ./tools/validators/ontology_validator/yamlformat
