# This workflow adds guids to any newly added entity types in the ontology and validates the ontology
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Ontology Validator

on:
  push:
    branches: [ master ]
    paths:
      - ontology/yaml/**

  pull_request:
    branches: [ master ]
    paths:
      - ontology/yaml/**
 
permissions:
    contents: write  # To push a branch 
    pull-requests: write  # To create a PR from that branch    

jobs:
  build:      
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout the branch the PR is coming from if PR
      if: ${{ github.event_name == 'pull_request' }}
      uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
#       with:
#         repository: ${{ github.event.pull_request.head.repo.full_name }}
#         ref: ${{ github.event.pull_request.head.ref }}
#         token: ${{secrets.BOT_TOKEN}}

    - name: Checkout head if push
      if: ${{ github.event_name == 'push' }}
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: '3.11'

    - name: Get modified entity type files
      id: changed-entity-type-files
      uses: tj-actions/changed-files@v35
      with:
        files: '**/ontology/yaml/**/entity_types/*.yaml'

    - name: Install dependencies for ontology YAML validator
      run: |
        python setup.py install
      working-directory: ./tools/validators/ontology_validator

    - name: Install dependencies for types GUID generator if any entity types files are changed
      if: steps.changed-entity-type-files.outputs.any_changed == 'true'
      run: |
        python setup.py install
      working-directory: ./tools/guid_generator/ontology

    - name: Run types GUID generator if any entity types files are changed
      if: steps.changed-entity-type-files.outputs.any_changed == 'true'
      run: |
        for file in ${{ steps.changed-entity-type-files.outputs.all_changed_files }}; do
          python types_guid_generator.py -f=../../../../$file
        done
      working-directory: ./tools/guid_generator/ontology/types_guid_generator
      
    - name: Commit files changed by types GUID generator
      run: |-
          git config user.name "db-robot"
          git config user.email "db-robot@google.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.BOT_TOKEN }}
        branch: ${{ github.ref }}
        
         # git push origin HEAD:${{ github.event.pull_request.head.ref }}
         # #${{ github.event.pull_request.head.repo.full_name }}:${{ github.event.pull_request.head.ref }}
#     - name: Commit files changed by types GUID generator
#       uses: EndBug/add-and-commit@v9
#       with:
#         author_name: db-robot
#         author_email: db-robot@google.com
#         message: 'Add GUIDs to new entity types'
      
    - name: Run ontology YAML validator on ontology extensions
      run: |
        python validator.py --original=../../../../ontology/yaml/resources  --interactive=False
      working-directory: ./tools/validators/ontology_validator/yamlformat
